services:

  site:
    image: ghcr.io/andgelbrissaud/poussieredantan:latest
    container_name: poussieredantan
    restart: unless-stopped

    labels:
      traefik.enable: "true"

      traefik.http.routers.poussieredantan.rule: "Host(`poussieredantan.com`) || Host(`www.poussieredantan.com`)"
      traefik.http.routers.poussieredantan.entrypoints: "web"

      traefik.http.services.poussieredantan.loadbalancer.server.port: "80"

    depends_on:
      - backend

    networks:
      - web


  backend:
    image: ghcr.io/andgelbrissaud/poussieredantan-backend:latest
    container_name: poussieredantan-backend
    restart: unless-stopped

    environment:
      NODE_ENV: production
      PORT: 3000

    volumes:
      - ./data:/app/data

    networks:
      - web



networks:

  web:
    external: true