services:

  site:
    image: ghcr.io/andgelbrissaud/poussieredantan:latest
    container_name: poussieredantan
    restart: unless-stopped

    ports:
      - "80:80"

    networks:
      - poussieredantan-network


  watchtower:
    image: nickfedor/watchtower
    container_name: poussieredantan-watchtower
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - C:/Users/Andge/.docker-watchtower/config.json:/config.json:ro

    environment:
      - DOCKER_CONFIG=/config

    command:
      - "--interval"
      - "300"
      - "poussieredantan"

    networks:
      - poussieredantan-network


  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: poussieredantan-cloudflared
    restart: unless-stopped

    volumes:
      - ./cloudflared:/etc/cloudflared

    command:
      - tunnel
      - --no-autoupdate
      - run
      - 9e6e3f2d-ed85-4534-9811-2bc3ce59edcf

    networks:
      - poussieredantan-network


networks:

  poussieredantan-network:
    driver: bridge