services:

  site:
    image: ghcr.io/andgelbrissaud/poussieredantan:latest
    container_name: poussieredantan
    ports:
      - "80:80"
    restart: unless-stopped


  watchtower:
    image: nickfedor/watchtower
    container_name: poussieredantan-watchtower
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command:
      - "--interval"
      - "300"
      - "poussieredantan"